spring:
  datasource:
    url: jdbc:mysql://mysql:3306/support_system?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Kavin@200424

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
gemini:
  api:
    key: AIzaSyBd8mCdUOR62kE4kObe_qMGrfObZfC0nuM

